[package]
name = "spider"
version = "1.1.1"
authors = ["madeindjs <contact@rousseau-alexandre.fr>"]
description = "Multithreaded Web spider crawler written in Rust."
repository = "https://github.com/madeindjs/spider"
readme = "README.md"
keywords = ["crawler", "spider"]
categories = ["web-programming"]
license = "MIT"
documentation = "https://docs.rs/spider"

[badges]
maintenance = { status = "as-is" }

[dependencies]
reqwest = "0.8.2"
scraper = "0.4.0"
robotparser = "0.10"
